version: '3.8'

services:
  rag_app:
    build: .
    ports:
      - "7860:7860"  # Gradioのポートをマッピング
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # ホストのdataディレクトリをコンテナ内にマウント
    restart: unless-stopped  # コンテナの再起動ポリシー
